module.exports = {

    //API Response Status Codes
    STATUS_CODE_SUCCESS: 200,
    STATUS_CODE_CREATED: 201,
    STATUS_CODE_NO_CONTENT: 204,
    STATUS_CODE_PARTIAL_CONTENT: 206,
    STATUS_CODE_INTERNAL_SERVER_ERROR: 500,
    STATUS_CODE_BAD_REQUEST: 400,
    STATUS_CODE_UNAUTHORIZED: 401,
    STATUS_CODE_NOT_ACCEPTABLE: 406,
    STATUS_CODE_UNPROCESSABLE_ENTITY: 422,
    STATUS_CODE_NOT_FOUND: 404,

}